### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by edewit** [MobileChromeApps/cordova-plugin-android-support-v4#3]
When other plugins depend on this it would be nice if they could depend on a particular version. A simple way to have this would be to create some tags, that way we have something stable and can upgrade and test when in a controlled way.

**Comment by imaffett** [comment]
@edewit  - you can tie to a specific commit in the plugin.xml - it doesn't look like this is maintained anymore.

**Comment by edewit** [comment]
To add it now you can use a framework tag in your plugin.xml
